# Generated by Django 5.2.17 on 2026-10-01 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='preferred_authors',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='books.author'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='books.genre'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_moods',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='books.mood'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
